POST http://localhost:3001/api/patients
Content-type :  application/json

{
  "name": "Test2",
  "dateOfBirth": "1971-04-09",
  "ssn": "090471-8850",
  "gender": "other",
  "occupation": "Stuff",
  "entries": []
}